### PR TITLE
Run CI on master branch & PR

### PR DESCRIPTION
**Pull request by jerone**
I noticed that you already converted Travis CI over to GitHub Actions. Was about to propose it too.
One thing missing here is to also run CI on Pull Requests.

### CODE REVIEW

**Comment by ryu1kn** [comment]
Hi @jerone , thanks for bringing this up 👍 

As for the optional manual run, I'm also not sure if we need it for now. Would you mind dropping it till we find we need it?

Also, I don't mind running the build for non-master branches; so we can go with `on: [push, pull_request]`. Thoughts?

**Comment by jerone** [comment]
> Also, I don't mind running the build for non-master branches; so we can go with `on: [push, pull_request]`. Thoughts?

[Pricing-wise](https://github.com/pricing) it doesn't matter how many times you run GitHub Actions (free for public repos).
But in my experience you want to limit the runs only to the main/master branch, so you can freely play on other branches. and not create noise until an PR is created (the moment you are happy to share your code changes).
I'm happy to go any way you want.

> Would you mind dropping it till we find we need it?

No problem. Will do it later today (not behind my laptop atm).

BTW, feel free to contribute (not alter) my branch if needed. Edits are allowed.

**Comment by ryu1kn** [comment]
Cheers! For long-running changes, I sometimes create a branch and I want CI feedback on it too. However, if I want to run CI, I guess I can just open a PR against `master` branch. Let's just keep them for `master` branches for now 👍

**Comment by jerone** [comment]
Removed the `workflow_dispatch`.

CI is now more in-line with `codeql-analysis.yml`.

**Comment by ryu1kn** [comment]
Thanks @jerone ! 👍

**Pull request merged**
