### PR TITLE
Update version to v1.3.0

### PR DESCRIPTION
**Pull request by jerone**

### CODE REVIEW

**Comment by jerone** [comment]
@ryu1kn Extension is ready for another release. :shipit: 

Because of no breaking changes, I increased the minor version.
See all changes in the [changelog](https://github.com/ryu1kn/vscode-extension-update-reporter/blob/master/CHANGELOG.md#unreleased).

~~Optionally, merge https://github.com/ryu1kn/vscode-extension-update-reporter/pull/49 if you approve.~~

I've tested all changes in latest stable VSCode and Insiders, plus all tests are ✅.

Feel free to alter the release date in the changelog and push to this branch.

**Comment by jerone** [comment]
Ping @ryu1kn

**Comment by jerone** [comment]
Ping @ryu1kn

**Comment by ryu1kn** [comment]
Thanks for keep updating the changelog as you work on PRs. Going to merge & publish this 👍

**Comment by ryu1kn** [comment]
Woohoo! Thank you @jerone 🎉🎉🎉

image

https://marketplace.visualstudio.com/items?itemName=ryu1kn.extension-update-reporter#overview

**Pull request merged**
